%YAML:1.0
---


directory_pattern_l: "/mnt/c/Data/Kitti/dataset/sequences/00/image_0/*.png"
directory_pattern_r: "/mnt/c/Data/Kitti/dataset/sequences/00/image_1/*.png"

sparse_detector:
  feature_extraction_algorithm: "ADAFAST"
  descriptor_compute_algorithm: "ORB"
  matcher_algorithm: "flann"
  
adafast:
  min_count: 200
  max_count: 1000
  min_threshold : 10
  max_threshold : 100
  cell_size_x : 3
  cell_size_y : 3
  thread_pool_size : 9
  threshold_step_size : 10

cam_params:
   stereo_cam_params:
      left_cam:
         K: !!opencv-matrix
            rows: 3
            cols: 3
            dt: d
            data: [ 7.1885599999999999e+02, 0., 6.0719280000000003e+02, 0.,
               7.1885599999999999e+02, 1.8521570000000000e+02, 0., 0., 1. ]
         dist_coeff: !!opencv-matrix
            rows: 1
            cols: 5
            dt: d
            data: [ 0., 0., 0., 0., 0. ]
      right_cam:
         K: !!opencv-matrix
            rows: 3
            cols: 3
            dt: d
            data: [ 7.1885599999999999e+02, 0., 6.0719280000000003e+02, 0.,
               7.1885599999999999e+02, 1.8521570000000000e+02, 0., 0., 1. ]
         dist_coeff: !!opencv-matrix
            rows: 1
            cols: 5
            dt: d
            data: [ 0., 0., 0., 0., 0. ]
      Rs: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 4.2768023855839997e-04, -9.9996724849459995e-01,
            -8.0844916834709995e-03, -7.2106265074969996e-03,
            8.0811984716450003e-03, -9.9994131645039996e-01,
            9.9997386459030002e-01, 4.8594858103900000e-04,
            -7.2069336924220004e-03 ]
      ts: !!opencv-matrix
         rows: 3
         cols: 1
         dt: d
         data: [ -1.1984599277130000e-02, -5.4039847297480001e-02,
            -2.9219686486860003e-01 ]
