%YAML:1.0
---


directory_pattern_l: "/mnt/c/Data/Kitti/dataset/sequences/00/image_0/*.png"
directory_pattern_r: "/mnt/c/Data/Kitti/dataset/sequences/00/image_1/*.png"

sparse_detector:
  feature_extraction_algorithm: "FAST"
  descriptor_compute_algorithm: "ORB"
  matcher_algorithm: "BF"

persistence:
   type: "IN_MEMORY"

io:
   type: "DISK"

adafast:
  min_count: 500
  max_count: 4000
  min_threshold : 10
  max_threshold : 120
  cell_size_x : 4
  cell_size_y : 4
  thread_pool_size : 9
  threshold_step_size : 10

cam_params:
   stereo_cam_params:
      left_cam:
         K: !!opencv-matrix
            rows: 3
            cols: 3
            dt: d
            data: [ 7.1885599999999999e+02, 0., 6.0719280000000003e+02, 0.,
               7.1885599999999999e+02, 1.8521570000000000e+02, 0., 0., 1. ]
         dist_coeff: !!opencv-matrix
            rows: 1
            cols: 5
            dt: d
            data: [ 0., 0., 0., 0., 0. ]
      right_cam:
         K: !!opencv-matrix
            rows: 3
            cols: 3
            dt: d
            data: [ 7.1885599999999999e+02, 0., 6.0719280000000003e+02, 0.,
               7.1885599999999999e+02, 1.8521570000000000e+02, 0., 0., 1. ]
         dist_coeff: !!opencv-matrix
            rows: 1
            cols: 5
            dt: d
            data: [ 0., 0., 0., 0., 0. ]
      Rs: !!opencv-matrix
         rows: 3
         cols: 3
         dt: d
         data: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]
      ts: !!opencv-matrix
         rows: 1
         cols: 3
         dt: d
         data: [ -5.3716571886441788e-01, 0., 0. ]
